engines:
  eslint:
    enabled: true
    channel: 'eslint-8'
    config:
      config: '.eslintrc.yaml'

ratings:
  paths:
    - '**.js'

checks:
  return-statements:
    enabled: false
  file-lines:
    config:
      threshold: 400
  method-lines:
    config:
      threshold: 30
  method-complexity:
    config:
      threshold: 10
